## aSSIST MBA_Python1_Review(1)

> **Q 1. np.arange를 사용해서 보폭 2의 정수 2부터 20까지 나타내는 1차원 배열을 만들어보세요.**

In [1]:
import numpy as np

In [4]:
#  np.arange를 사용해서 보폭 2의 정수 2부터 20까지 나타내는 1차원 배열 생성.
array = np.arange(2, 20, 2)
print(array.astype)
# Print the array.
print(array)

<built-in method astype of numpy.ndarray object at 0x7fd9b432de10>
[ 2  4  6  8 10 12 14 16 18]


> **Q 2. randint함수를 이용해 100~500사이의 수로 4x5 행렬을 만들어보세요.**

In [3]:
# randint함수를 이용해 100~500사이의 수로 4x5 행렬 생성
matrix = np.random.randint(100, 500, (4, 5))

# Print the matrix.
print(matrix)

[[415 122 483 126 390]
 [242 205 331 372 463]
 [313 282 444 136 397]
 [300 321 428 262 405]]


### 수업시간에 활용했던 'apt.csv' 파일을 불러와 다음의 조건에 맞는 결과물을 출력해 보세요.(Q 3~Q 5)

In [17]:
# 'apt.csv' 파일을 불러오기
import pandas as pd
from pandas import DataFrame, Series 

In [18]:
# 데이터 불러오기(read_csv() 사용) 
# encoding error CP949 또는 utf-8
apt = pd.read_csv('./Data/apt.csv', encoding='CP949')
apt.head()

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층  \
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5   
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   
3  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   12  20600   3   
4  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   20  20500   1   

   건축년도           도로명  
0  1997   경강로2539번길 8  
1  1997   경강로2539번길 8  
2  2005  경강로2539번길 22  
3  2005  경강로2539번길 22  
4  2005  경강로2539번길 22

> **Q 3. loc 함수를 이용해 25억 원을 초과하는 가격으로 거래된 아파트의 지역, 아파트명, 가격을 출력해 보세요.**

In [19]:
apt.loc[apt['가격'] > 25000, ['지역','아파트','가격']]

지역              아파트     가격
5        강원도 강릉시 교동  강릉 교동 풍림아이원 아파트  29200
6        강원도 강릉시 교동      강릉교동롯데캐슬1단지  34300
7        강원도 강릉시 교동      강릉교동롯데캐슬2단지  32500
22       강원도 강릉시 교동         교동이-편한세상  32500
38       강원도 강릉시 교동            현대하이빌  28500
...             ...              ...    ...
42665  충청북도 충주시 연수동          연수힐스테이트  27200
42666  충청북도 충주시 연수동          연수힐스테이트  26500
42670  충청북도 충주시 연수동        충주센트럴푸르지오  28500
42671  충청북도 충주시 연수동        충주센트럴푸르지오  29800
42748  충청북도 충주시 호암동          우미린에듀시티  35400

[21609 rows x 3 columns]

> **Q 4. '단가'라는 column을 만들고 '단가'를 내림차순으로 정리했을 경우, 이들 중 20억 원을 초과하는 아파트의 '지역', '아파트', '면적', '가격','단가' 데이터를 출력해 보세요.**

In [20]:
apt['단가'] = apt['가격'] / apt['면적']
apt.head()

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층  \
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5   
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   
3  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   12  20600   3   
4  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   20  20500   1   

   건축년도           도로명          단가  
0  1997   경강로2539번길 8  182.274247  
1  1997   경강로2539번길 8  159.242522  
2  2005  경강로2539번길 22  294.152253  
3  2005  경강로2539번길 22  242.381457  
4  2005  경강로2539번길 22  241.204848

In [21]:
filtered_price_df = apt.sort_values("단가", ascending=False)
filtered_price_df.head()

지역   번지   본번  부번       아파트     면적    계약년월  계약일      가격  층  \
27011  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  35.87  201910   31  196000  3   
27009  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  50.64  201910   12  270000  5   
27008  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  42.55  201910    4  207000  2   
27007  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  42.55  201910    3  205000  4   
27006  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  35.64  201910    2  153000  2   

       건축년도      도로명           단가  
27011  1982  개포로 310  5464.176192  
27009  1982  개포로 310  5331.753555  
27008  1982  개포로 310  4864.864865  
27007  1982  개포로 310  4817.861340  
27006  1982  개포로 310  4292.929293

In [22]:
filtered_price_df[filtered_price_df['가격'] > 20000, ['지역', '아파트', '면적', '가격','단가']]

InvalidIndexError: (27011     True
27009     True
27008     True
27007     True
27006     True
         ...  
17027    False
17025    False
17032    False
17024    False
17022    False
Name: 가격, Length: 42758, dtype: bool, ['지역', '아파트', '면적', '가격', '단가'])

> **Q 5. '지역'에서 '부산광역시'를 포함하는 데이터들만 따로 추출해 '부산.csv'파일을 만들고 '단가' 기준 내림차순으로 정렬할 경우, Top5의 '지역','아파트','가격','면적' 데이터를 출력해 보세요.**