## aSSIST MBA_Python1_Review(1)

> **Q 1. np.arange를 사용해서 보폭 2의 정수 2부터 20까지 나타내는 1차원 배열을 만들어보세요.**

In [1]:
import numpy as np

In [2]:
#  np.arange를 사용해서 보폭 2의 정수 2부터 20까지 나타내는 1차원 배열 생성.
array = np.arange(2, 20, 2)
print(array.astype)
# Print the array.
print(array)

<built-in method astype of numpy.ndarray object at 0x7f3e196ca6f0>
[ 2  4  6  8 10 12 14 16 18]


> **Q 2. randint함수를 이용해 100~500사이의 수로 4x5 행렬을 만들어보세요.**

In [3]:
# randint함수를 이용해 100~500사이의 수로 4x5 행렬 생성
matrix = np.random.randint(100, 500, (4, 5))

# Print the matrix.
print(matrix)

[[477 233 137 344 220]
 [300 333 147 146 325]
 [410 176 482 340 359]
 [123 182 238 314 433]]


### 수업시간에 활용했던 'apt.csv' 파일을 불러와 다음의 조건에 맞는 결과물을 출력해 보세요.(Q 3~Q 5)

In [4]:
# 'apt.csv' 파일을 불러오기
import pandas as pd
from pandas import DataFrame, Series 

In [5]:
# 데이터 불러오기(read_csv() 사용) 
# encoding error CP949 또는 utf-8
apt = pd.read_csv('./Data/apt.csv', encoding='CP949')
apt.head()

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층   
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5  \
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   
3  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   12  20600   3   
4  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   20  20500   1   

   건축년도           도로명  
0  1997   경강로2539번길 8  
1  1997   경강로2539번길 8  
2  2005  경강로2539번길 22  
3  2005  경강로2539번길 22  
4  2005  경강로2539번길 22

> **Q 3. loc 함수를 이용해 25억 원을 초과하는 가격으로 거래된 아파트의 지역, 아파트명, 가격을 출력해 보세요.**

In [6]:
apt.loc[apt['가격'] > 25000, ['지역','아파트','가격']]

지역              아파트     가격
5        강원도 강릉시 교동  강릉 교동 풍림아이원 아파트  29200
6        강원도 강릉시 교동      강릉교동롯데캐슬1단지  34300
7        강원도 강릉시 교동      강릉교동롯데캐슬2단지  32500
22       강원도 강릉시 교동         교동이-편한세상  32500
38       강원도 강릉시 교동            현대하이빌  28500
...             ...              ...    ...
42665  충청북도 충주시 연수동          연수힐스테이트  27200
42666  충청북도 충주시 연수동          연수힐스테이트  26500
42670  충청북도 충주시 연수동        충주센트럴푸르지오  28500
42671  충청북도 충주시 연수동        충주센트럴푸르지오  29800
42748  충청북도 충주시 호암동          우미린에듀시티  35400

[21609 rows x 3 columns]

> **Q 4. '단가'라는 column을 만들고 '단가'를 내림차순으로 정리했을 경우, 이들 중 20억 원을 초과하는 아파트의 '지역', '아파트', '면적', '가격','단가' 데이터를 출력해 보세요.**

In [7]:
apt['단가'] = apt['가격'] / apt['면적']
apt.head()

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층   
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5  \
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   
3  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   12  20600   3   
4  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910   20  20500   1   

   건축년도           도로명          단가  
0  1997   경강로2539번길 8  182.274247  
1  1997   경강로2539번길 8  159.242522  
2  2005  경강로2539번길 22  294.152253  
3  2005  경강로2539번길 22  242.381457  
4  2005  경강로2539번길 22  241.204848

In [8]:
filtered_price_df = apt.sort_values(by = '단가', ascending=False)
filtered_price_df.head()

지역   번지   본번  부번       아파트     면적    계약년월  계약일      가격  층   
27011  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  35.87  201910   31  196000  3  \
27009  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  50.64  201910   12  270000  5   
27008  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  42.55  201910    4  207000  2   
27007  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  42.55  201910    3  205000  4   
27006  서울특별시 강남구 개포동  141  141   0  개포주공 1단지  35.64  201910    2  153000  2   

       건축년도      도로명           단가  
27011  1982  개포로 310  5464.176192  
27009  1982  개포로 310  5331.753555  
27008  1982  개포로 310  4864.864865  
27007  1982  개포로 310  4817.861340  
27006  1982  개포로 310  4292.929293

In [9]:
filtered_price_df.loc[filtered_price_df['가격'] > 200000, ['지역', '아파트', '면적', '가격','단가']]

지역       아파트       면적      가격           단가
27009  서울특별시 강남구 개포동  개포주공 1단지   50.640  270000  5331.753555
27008  서울특별시 강남구 개포동  개포주공 1단지   42.550  207000  4864.864865
27007  서울특별시 강남구 개포동  개포주공 1단지   42.550  205000  4817.861340
29945  서울특별시 서초구 반포동   아크로리버파크   84.950  340000  4002.354326
29943  서울특별시 서초구 반포동   아크로리버파크   59.980  206000  3434.478159
...              ...       ...      ...     ...          ...
30019  서울특별시 서초구 서초동     현대슈퍼빌  214.920  250000  1163.223525
35826  인천광역시 연수구 송도동  더샵센트럴파크2  291.336  300000  1029.738858
27118  서울특별시 강남구 역삼동    롯데캐슬노블  242.820  245000  1008.977844
31501   서울특별시 중구 신당동    벨레어카운티  273.820  240000   876.488204
30002  서울특별시 서초구 서초동    서초프레스턴  244.420  206000   842.811554

[76 rows x 5 columns]

> **Q 5. '지역'에서 '부산광역시'를 포함하는 데이터들만 따로 추출해 '부산.csv'파일을 만들고 '단가' 기준 내림차순으로 정렬할 경우, Top5의 '지역','아파트','가격','면적' 데이터를 출력해 보세요.**

In [10]:
filtered_price_df.loc[(filtered_price_df.지역.str.find('부산광역시') > -1)]

지역        번지    본번   부번          아파트        면적    계약년월   
26805   부산광역시 해운대구 우동      1407  1407    0  해운대두산위브더제니스  209.8332  201910  \
24692    부산광역시 남구 대연동      1808  1808    0         대연비치   42.9300  201910   
26293   부산광역시 수영구 남천동     148-4   148    4         삼익비치   41.5200  201910   
26305   부산광역시 수영구 남천동     148-4   148    4         삼익비치   41.5200  201910   
26301   부산광역시 수영구 남천동     148-4   148    4         삼익비치   41.5200  201910   
...               ...       ...   ...  ...          ...       ...     ...   
24878    부산광역시 남구 용호동     산20-1    20    1         한라임대   56.4000  201910   
26474   부산광역시 연제구 연산동  1135-127  1135  127           동우   41.9100  201910   
25484    부산광역시 북구 구포동    1243-9  1243    9           백양   82.7400  201910   
24903    부산광역시 동구 수정동    1181-4  1181    4   수정(1181-4)   36.3600  201910   
26647  부산광역시 중구 보수동1가    산3-148     3  148           시영   36.3600  201910   

       계약일      가격   층  건축년도              도로명           단가  
26805   16  376640  70  2011        마린시티2로 33  1794.949512  
24692   23   45000   9  1984         황령대로 504  1048.218029  
26293   12   43000   8  1979        광안해변로 100  1035.645472  
26305   26   43000   9  1979        광안해변로 100  1035.645472  
26301   21   42750   7  1979        광안해변로 100  1029.624277  
...    ...     ...  ..   ...              ...          ...  
24878   16    4950   5  1987  이기대공원로26번길 21-7    87.765957  
26474    4    3600   5  1990      쌍미천로84번길 86    85.898354  
25484   15    7000   3  1992          시랑로 183    84.602369  
24903   21    2000   1  1962    망양로685번길 30-3    55.005501  
26647   22    1500   1  1969      망양로319번길 24    41.254125  

[2752 rows x 13 columns]

In [11]:
filtered_price_df.loc[(filtered_price_df.지역.str.find('부산광역시') > -1)].to_csv("Data/부산.csv")

In [12]:
busan_apt = pd.read_csv('./Data/부산.csv')
busan_apt.head()

Unnamed: 0             지역     번지    본번  부번          아파트        면적    계약년월   
0       26805  부산광역시 해운대구 우동   1407  1407   0  해운대두산위브더제니스  209.8332  201910  \
1       24692   부산광역시 남구 대연동   1808  1808   0         대연비치   42.9300  201910   
2       26293  부산광역시 수영구 남천동  148-4   148   4         삼익비치   41.5200  201910   
3       26305  부산광역시 수영구 남천동  148-4   148   4         삼익비치   41.5200  201910   
4       26301  부산광역시 수영구 남천동  148-4   148   4         삼익비치   41.5200  201910   

   계약일      가격   층  건축년도        도로명           단가  
0   16  376640  70  2011  마린시티2로 33  1794.949512  
1   23   45000   9  1984   황령대로 504  1048.218029  
2   12   43000   8  1979  광안해변로 100  1035.645472  
3   26   43000   9  1979  광안해변로 100  1035.645472  
4   21   42750   7  1979  광안해변로 100  1029.624277

In [13]:
busan_apt.sort_values(by = '단가', ascending = False).loc[:4,('지역','아파트','가격','면적','단가')]   

지역          아파트      가격        면적           단가
0  부산광역시 해운대구 우동  해운대두산위브더제니스  376640  209.8332  1794.949512
1   부산광역시 남구 대연동         대연비치   45000   42.9300  1048.218029
2  부산광역시 수영구 남천동         삼익비치   43000   41.5200  1035.645472
3  부산광역시 수영구 남천동         삼익비치   43000   41.5200  1035.645472
4  부산광역시 수영구 남천동         삼익비치   42750   41.5200  1029.624277